version: '3'
networks:
    kingmobnet:
        external: true
services:
    calibre:
        env_file:
            - '/changan/docker/changan.env'
        image: linuxserver/calibre-web
        user: root
        networks:
            - kingmobnet
        ports:
            - '9342:8083'
        volumes:
            - '${CONFIG}/calibre/:/config'
            - '${DOWNLOADS}/calibre-web/:/downloads'
            - '${MEDIA}/Books/:/books'
        environment:
            TZ: ${TZ}
    kodi:
        env_file:
            - '/changan/docker/changan.env'
        image: linuxserver/kodi-headless
        user: root
        networks:
            - kingmobnet
        ports:
            - '9380:8080'
            - '9390:9090'
            - '9777:9777/udp'
        volumes:
            - '${CONFIG}/kodi/:/config/.kodi'
            - '${MEDIA}/:/media'
        environment:
            TZ: ${TZ}
