version: '3'
networks:
    kingmobnet:
        external: true
services:
    mariadb:
        env_file:
            - '/changan/docker/changan.env'
        image: linuxserver/mariadb
        user: root
        networks:
            - kingmobnet
        ports:
            - '3306:3306'
        volumes:
            - '${CONFIG}/mariadb/:/config'
        environment:
            TZ: ${TZ}
            MYSQL_ROOT_PASSWORD: ${DBROOT}
    phpmyadmin:
        env_file:
            - '/changan/docker/changan.env'
        image: phpmyadmin/phpmyadmin
        user: root
        networks:
            - kingmobnet
        ports:
            - '9350:80'
        environment:
            TZ: ${TZ}
            PMA_HOST: mariadb
            MYSQL_ROOT_PASSWORD: ${DBROOT}
